### ISSUE TITLE
set_fact is not defined with a name for logging

### ISSUE THREAD

**Issue by titom73** [titom73/vagrant-ansible-demo#3]
```
    tasks:
      - set_fact: 
          build_dir: "{{ build_dir }}/{{ inventory_hostname }}/tmp"
          junos_conf: "{{ build_dir }}/{{ inventory_hostname}}/junos.conf"
      - name: remove host build temp directory
        file: path={{ build_dir }} state=absent
      - name: create host build temp directory
        file: path={{ build_dir }} state=directory
```
